name: Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build ${{ matrix.target }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: bc
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: bc.exe
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: bc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "::set-env name=PKG_CONFIG_ALLOW_CROSS::1"
          sudo apt-get install -y musl-tools
      - name: Checkout
        uses: actions/checkout@v1

      - name: Fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
          args: --target ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        id: package
        shell: bash -e {0}
        run: |
          name=barnacle
          tag=$(git describe --tags --abbrev=0)
          release_name="$name-$tag-${{ matrix.target }}"
          release_tar="${release_name}.tar.gz"
          mkdir "$release_name"
          if [ "${{ matrix.target }}" != "x86_64-pc-windows-msvc" ]; then
              strip "target/${{ matrix.target }}/release/${{ matrix.bin }}"
          fi
          cp target/${{ matrix.target }}/release/${{ matrix.bin }} "$release_name"
          
          echo "::set-output name=TAR::$release_name"

      - name: Zip Package
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a -t7z -mx=9 ${{ steps.package.outputs.TAR }}.7z ./${{ steps.package.outputs.TAR }}/

      - name: Hash
        id: hash
        shell: bash -e {0}
        run: |
          release_tar="${{ steps.package.outputs.TAR }}.7z"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "(Get-FileHash \"${release_tar}\" -Algorithm SHA256).Hash | Out-File -Encoding ASCII -NoNewline \"${release_tar}.sha256\"" | pwsh -c -
          else
            echo -n "$(shasum -ba 256 "${release_tar}" | cut -d " " -f 1)" > "${release_tar}.sha256"
          fi

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          body: 'Automatically deployed release'
          # draft: true
          files: 'barnacle*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}